source 'https://rubygems.org'

gem 'rails', '~> 4.2.1'
gem 'pg', '~> 0.18.1'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails', '~> 4.0.3'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bootstrap-sass', '~> 3.3.4.1'
gem 'typhoeus', '~> 0.7.1'
gem 'oj', '~> 2.12.1'
gem 'twitter', '~> 5.14.0'

group :development do
  gem 'capistrano', '~> 3.4.0'
  gem 'capistrano-rails', '~> 1.1.2'
  gem 'capistrano-rvm', '~> 0.1.2'
end

group :development, :test do
  gem 'web-console', '~> 2.0'
  gem 'spring', '~> 1.3.3'
  gem 'pry', '~> 0.10.1'
  gem 'dotenv-rails', '~> 2.0.0'
end

group :test do
  gem 'rspec-rails', '~> 3.2.1'
  gem 'capybara', '~> 2.4.4'
  gem 'webmock', '~> 1.20.4'
  gem 'vcr', '~> 2.9.3'
end

